# Generated by Django 4.2.8 on 2024-01-05 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0004_alter_todo_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='creator',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
