# Generated by Django 4.2.8 on 2024-01-05 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0005_todo_creator'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateKeep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(default='0', max_length=50)),
            ],
        ),
    ]
