# Generated by Django 3.2.6 on 2023-03-27 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase_Requisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requesting_department', models.CharField(max_length=220)),
                ('request_justification', models.CharField(max_length=120)),
                ('name_of_supplier', models.CharField(max_length=220)),
                ('name_address_of_supplier', models.DateField(auto_now_add=True)),
                ('budget_line_item', models.CharField(max_length=220)),
                ('qty', models.CharField(max_length=220)),
                ('item_no', models.CharField(max_length=220)),
                ('description', models.CharField(max_length=220)),
                ('unit_price', models.CharField(max_length=220)),
                ('total', models.CharField(max_length=220)),
                ('signature_of_requestor', models.CharField(max_length=220)),
                ('date_requestor', models.DateField(auto_now_add=True)),
                ('signature_of_supervisor_pi', models.CharField(max_length=220)),
                ('date_supervisor_pi', models.DateField(auto_now_add=True)),
                ('Signature_of_accounts_cleck', models.CharField(max_length=220)),
                ('date_accounts_cleck', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
