<<<<<<< HEAD
# Generated by Django 4.1.7 on 2023-03-27 13:02
=======
# Generated by Django 3.2.6 on 2023-03-27 12:38
>>>>>>> 4db80039bb00407c8d8198d042496bf317a9bc6e

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='ComparativeSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(default='username', max_length=30)),
                ('payee', models.CharField(default='takaengwa@gmail.com', max_length=150)),
                ('company_name_supplier1', models.CharField(default='takaengwa@gmail.com', max_length=450)),
                ('company_name_supplier2', models.CharField(default='takaengwa@gmail.com', max_length=450)),
                ('company_name_supplier3', models.CharField(default='takaengwa@gmail.com', max_length=450)),
                ('item_number_supplier1', models.CharField(default='takaengwa@gmail.com', max_length=450)),
                ('item_number_supplier2', models.CharField(default='takaengwa@gmail.com', max_length=450)),
                ('item_number_supplier3', models.CharField(default='takaengwa@gmail.com', max_length=450)),
                ('desc_supplier1', models.CharField(default='takaengwa@gmail.com', max_length=450)),
                ('desc_supplier2', models.CharField(default='takaengwa@gmail.com', max_length=450)),
                ('desc_supplier3', models.CharField(default='takaengwa@gmail.com', max_length=450)),
                ('qnty_supplier1', models.CharField(default='takaengwa@gmail.com', max_length=450)),
                ('qnty_supplier2', models.CharField(default='takaengwa@gmail.com', max_length=450)),
                ('qnty_supplier3', models.CharField(default='takaengwa@gmail.com', max_length=450)),
                ('unit_price_supplier1', models.CharField(default='takaengwa@gmail.com', max_length=450)),
                ('unit_price_supplier2', models.CharField(default='takaengwa@gmail.com', max_length=450)),
                ('unit_price_supplier3', models.CharField(default='takaengwa@gmail.com', max_length=450)),
                ('total_price_supplier1', models.CharField(default='takaengwa@gmail.com', max_length=450)),
                ('total_price_supplier2', models.CharField(default='takaengwa@gmail.com', max_length=450)),
                ('total_price_supplier3', models.CharField(default='takaengwa@gmail.com', max_length=450)),
                ('recommended_supplier', models.CharField(default='2023', max_length=15)),
                ('recommended_supplier_reason', models.CharField(default='takaengwa@gmail.com', max_length=150)),
                ('dpt_project_requesting', models.CharField(default='2023', max_length=15)),
                ('requested_by', models.CharField(default='username', max_length=30)),
                ('requested_by_sig', models.CharField(default='username', max_length=30)),
                ('requested_by_date', models.CharField(default='username', max_length=30)),
                ('tech_person_by', models.CharField(default='username', max_length=30)),
                ('tech_person_by_sig', models.CharField(default='username', max_length=30)),
                ('tech_person_date', models.CharField(default='username', max_length=30)),
                ('dpt_head_by', models.CharField(default='username', max_length=30)),
                ('dpt_head_by_sig', models.CharField(default='username', max_length=30)),
                ('dpt_head_date', models.CharField(default='username', max_length=30)),
                ('team_lead_by', models.CharField(default='username', max_length=30)),
                ('team_lead_by_sig', models.CharField(default='username', max_length=30)),
                ('team_lead_date', models.CharField(default='username', max_length=30)),
                ('approved_by', models.CharField(default='username', max_length=30)),
                ('approved_by_sig', models.CharField(default='username', max_length=30)),
                ('approved_date', models.CharField(default='username', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(default='username', max_length=30)),
                ('compiled_by', models.CharField(default='username', max_length=30)),
                ('date_of_request', models.CharField(default='2023', max_length=15)),
                ('payee', models.CharField(default='takaengwa@gmail.com', max_length=150)),
                ('payment_type', models.CharField(default='takaengwa@gmail.com', max_length=450)),
                ('project_number', models.CharField(default='takaengwa@gmail.com', max_length=150)),
                ('account_code', models.CharField(default='takaengwa@gmail.com', max_length=150)),
                ('details', models.CharField(default='takaengwa@gmail.com', max_length=150)),
                ('amount', models.CharField(default='takaengwa@gmail.com', max_length=150)),
                ('total', models.CharField(default='takaengwa@gmail.com', max_length=150)),
                ('certified_by', models.CharField(default='.', max_length=150)),
                ('certified_by_date', models.CharField(default='.', max_length=150)),
                ('cleared_by_fin_man', models.CharField(default='.', max_length=150)),
                ('cleared_by_fin_man_date', models.CharField(default='.', max_length=150)),
                ('approved_by_project_man', models.CharField(default='.', max_length=150)),
                ('approved_by_project_man_date', models.CharField(default='.', max_length=150)),
                ('approved_by', models.CharField(default='.', max_length=150)),
                ('approved_by_date', models.CharField(default='.', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='PuchaseRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(default='username', max_length=30)),
                ('requester', models.CharField(default='username', max_length=30)),
                ('date_of_request', models.CharField(default='2023', max_length=15)),
                ('requesting_dpt', models.CharField(default='takaengwa@gmail.com', max_length=150)),
                ('request_justification', models.CharField(default='takaengwa@gmail.com', max_length=450)),
                ('name_address_of_supplier', models.CharField(default='takaengwa@gmail.com', max_length=550)),
                ('budget_line_item', models.CharField(default='takaengwa@gmail.com', max_length=150)),
                ('qnty', models.CharField(default='takaengwa@gmail.com', max_length=150)),
                ('item_number', models.CharField(default='takaengwa@gmail.com', max_length=150)),
                ('description', models.CharField(default='takaengwa@gmail.com', max_length=150)),
                ('unit_price', models.CharField(default='takaengwa@gmail.com', max_length=150)),
                ('total', models.CharField(default='takaengwa@gmail.com', max_length=150)),
                ('supervisor_approved', models.CharField(default='.', max_length=150)),
                ('supervisor_approved_date', models.CharField(default='.', max_length=150)),
                ('accounts_clerk_approved', models.CharField(default='.', max_length=150)),
                ('accounts_clerk_approved_date', models.CharField(default='.', max_length=150)),
=======
            name='Purchase_Requisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requesting_department', models.CharField(max_length=220)),
                ('request_justification', models.CharField(max_length=120)),
                ('name_of_supplier', models.CharField(max_length=220)),
                ('name_address_of_supplier', models.DateField(auto_now_add=True)),
                ('budget_line_item', models.CharField(max_length=220)),
                ('qty', models.CharField(max_length=220)),
                ('item_no', models.CharField(max_length=220)),
                ('description', models.CharField(max_length=220)),
                ('unit_price', models.CharField(max_length=220)),
                ('total', models.CharField(max_length=220)),
                ('signature_of_requestor', models.CharField(max_length=220)),
                ('date_requestor', models.DateField(auto_now_add=True)),
                ('signature_of_supervisor_pi', models.CharField(max_length=220)),
                ('date_supervisor_pi', models.DateField(auto_now_add=True)),
                ('Signature_of_accounts_cleck', models.CharField(max_length=220)),
                ('date_accounts_cleck', models.DateField(auto_now_add=True)),
>>>>>>> 4db80039bb00407c8d8198d042496bf317a9bc6e
            ],
        ),
    ]
