# Generated by Django 4.2.8 on 2024-01-22 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetLines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('project', models.CharField(blank=True, max_length=255)),
                ('code', models.CharField(blank=True, max_length=255)),
                ('amount', models.CharField(blank=True, max_length=255)),
                ('balance', models.CharField(blank=True, max_length=255)),
                ('subtract', models.CharField(blank=True, max_length=255)),
                ('added_by', models.CharField(blank=True, max_length=255)),
                ('added_by_date', models.CharField(blank=True, max_length=255)),
                ('dpt', models.CharField(blank=True, max_length=255)),
                ('last_used', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('head', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('code', models.CharField(blank=True, max_length=255)),
                ('duration', models.CharField(blank=True, max_length=255)),
                ('start_date', models.CharField(blank=True, max_length=255)),
                ('end_date', models.CharField(blank=True, max_length=255)),
                ('manager', models.CharField(blank=True, max_length=255)),
                ('pi', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='goodsreceivednote',
            name='rejector',
            field=models.CharField(default='None', max_length=150),
        ),
        migrations.AddField(
            model_name='goodsreceivednote',
            name='rejector_date',
            field=models.CharField(default='None', max_length=500),
        ),
        migrations.AddField(
            model_name='goodsreceivednote',
            name='rejector_message',
            field=models.CharField(default='None', max_length=500),
        ),
        migrations.AddField(
            model_name='supplier',
            name='added_by',
            field=models.CharField(default='.', max_length=150),
        ),
        migrations.AddField(
            model_name='supplier',
            name='added_by_date',
            field=models.CharField(default='.', max_length=150),
        ),
        migrations.AddField(
            model_name='supplier',
            name='alt_contact_number',
            field=models.CharField(default='None', max_length=150),
        ),
        migrations.AddField(
            model_name='supplier',
            name='approved_by',
            field=models.CharField(default='.', max_length=150),
        ),
        migrations.AddField(
            model_name='supplier',
            name='approved_by_date',
            field=models.CharField(default='.', max_length=150),
        ),
        migrations.AddField(
            model_name='supplier',
            name='evaluated',
            field=models.CharField(default='.', max_length=150),
        ),
        migrations.AddField(
            model_name='supplier',
            name='evaluated_by',
            field=models.CharField(default='.', max_length=150),
        ),
        migrations.AddField(
            model_name='supplier',
            name='evaluated_by_date',
            field=models.CharField(default='.', max_length=150),
        ),
        migrations.AddField(
            model_name='supplier',
            name='evaluation_decision',
            field=models.CharField(default='.', max_length=150),
        ),
        migrations.AddField(
            model_name='supplier',
            name='meta_data',
            field=models.CharField(default='None', max_length=1500),
        ),
        migrations.AddField(
            model_name='supplier',
            name='tax_complient',
            field=models.CharField(default='.', max_length=150),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='address',
            field=models.CharField(default='None', max_length=300),
        ),
    ]
