# Generated by Django 4.2.8 on 2024-04-03 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_num', models.CharField(blank=True, max_length=255)),
                ('rider_name', models.CharField(blank=True, max_length=255)),
                ('witness', models.CharField(blank=True, max_length=255)),
                ('date_of_record', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
