# Generated by Django 4.1.7 on 2023-03-29 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comparativeschedule',
            name='company_name_supplier1',
            field=models.CharField(default='.', max_length=450),
        ),
        migrations.AlterField(
            model_name='comparativeschedule',
            name='company_name_supplier2',
            field=models.CharField(default='.', max_length=450),
        ),
        migrations.AlterField(
            model_name='comparativeschedule',
            name='company_name_supplier3',
            field=models.CharField(default='.', max_length=450),
        ),
        migrations.AlterField(
            model_name='comparativeschedule',
            name='desc_supplier1',
            field=models.CharField(default='.', max_length=450),
        ),
        migrations.AlterField(
            model_name='comparativeschedule',
            name='desc_supplier2',
            field=models.CharField(default='.', max_length=450),
        ),
        migrations.AlterField(
            model_name='comparativeschedule',
            name='desc_supplier3',
            field=models.CharField(default='.', max_length=450),
        ),
        migrations.AlterField(
            model_name='comparativeschedule',
            name='item_number_supplier1',
            field=models.CharField(default='.', max_length=450),
        ),
        migrations.AlterField(
            model_name='comparativeschedule',
            name='item_number_supplier2',
            field=models.CharField(default='.', max_length=450),
        ),
        migrations.AlterField(
            model_name='comparativeschedule',
            name='item_number_supplier3',
            field=models.CharField(default='.', max_length=450),
        ),
        migrations.AlterField(
            model_name='comparativeschedule',
            name='payee',
            field=models.CharField(default='.', max_length=150),
        ),
        migrations.AlterField(
            model_name='comparativeschedule',
            name='project_number',
            field=models.CharField(default='.', max_length=150),
        ),
        migrations.AlterField(
            model_name='comparativeschedule',
            name='qnty_supplier1',
            field=models.CharField(default='.', max_length=450),
        ),
        migrations.AlterField(
            model_name='comparativeschedule',
            name='qnty_supplier2',
            field=models.CharField(default='.', max_length=450),
        ),
        migrations.AlterField(
            model_name='comparativeschedule',
            name='qnty_supplier3',
            field=models.CharField(default='.', max_length=450),
        ),
        migrations.AlterField(
            model_name='comparativeschedule',
            name='recommended_supplier_reason',
            field=models.CharField(default='.', max_length=150),
        ),
        migrations.AlterField(
            model_name='comparativeschedule',
            name='total_price_supplier1',
            field=models.CharField(default='.', max_length=450),
        ),
        migrations.AlterField(
            model_name='comparativeschedule',
            name='total_price_supplier2',
            field=models.CharField(default='.', max_length=450),
        ),
        migrations.AlterField(
            model_name='comparativeschedule',
            name='total_price_supplier3',
            field=models.CharField(default='.', max_length=450),
        ),
        migrations.AlterField(
            model_name='comparativeschedule',
            name='unit_price_supplier1',
            field=models.CharField(default='.', max_length=450),
        ),
        migrations.AlterField(
            model_name='comparativeschedule',
            name='unit_price_supplier2',
            field=models.CharField(default='.', max_length=450),
        ),
        migrations.AlterField(
            model_name='comparativeschedule',
            name='unit_price_supplier3',
            field=models.CharField(default='.', max_length=450),
        ),
        migrations.AlterField(
            model_name='paymentrequest',
            name='account_code',
            field=models.CharField(default='.', max_length=150),
        ),
        migrations.AlterField(
            model_name='paymentrequest',
            name='amount',
            field=models.CharField(default='.', max_length=150),
        ),
        migrations.AlterField(
            model_name='paymentrequest',
            name='details',
            field=models.CharField(default='.', max_length=150),
        ),
        migrations.AlterField(
            model_name='paymentrequest',
            name='payee',
            field=models.CharField(default='.', max_length=150),
        ),
        migrations.AlterField(
            model_name='paymentrequest',
            name='payment_type',
            field=models.CharField(default='.', max_length=450),
        ),
        migrations.AlterField(
            model_name='paymentrequest',
            name='project_number',
            field=models.CharField(default='.', max_length=150),
        ),
        migrations.AlterField(
            model_name='paymentrequest',
            name='total',
            field=models.CharField(default='.', max_length=150),
        ),
        migrations.AlterField(
            model_name='puchaserequest',
            name='budget_line_item',
            field=models.CharField(default='.', max_length=150),
        ),
        migrations.AlterField(
            model_name='puchaserequest',
            name='description',
            field=models.CharField(default='.', max_length=150),
        ),
        migrations.AlterField(
            model_name='puchaserequest',
            name='item_number',
            field=models.CharField(default='.', max_length=150),
        ),
        migrations.AlterField(
            model_name='puchaserequest',
            name='name_address_of_supplier',
            field=models.CharField(default='.', max_length=550),
        ),
        migrations.AlterField(
            model_name='puchaserequest',
            name='qnty',
            field=models.CharField(default='.', max_length=150),
        ),
        migrations.AlterField(
            model_name='puchaserequest',
            name='request_justification',
            field=models.CharField(default='.', max_length=450),
        ),
        migrations.AlterField(
            model_name='puchaserequest',
            name='requesting_dpt',
            field=models.CharField(default='.', max_length=150),
        ),
        migrations.AlterField(
            model_name='puchaserequest',
            name='total',
            field=models.CharField(default='.', max_length=150),
        ),
        migrations.AlterField(
            model_name='puchaserequest',
            name='unit_price',
            field=models.CharField(default='.', max_length=150),
        ),
    ]
