# Generated by Django 3.2.6 on 2023-09-28 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrequest',
            name='completed',
            field=models.CharField(default='0', max_length=5),
        ),
        migrations.AlterField(
            model_name='compschedulequotation',
            name='quote1_path',
            field=models.CharField(default='#', max_length=500),
        ),
        migrations.AlterField(
            model_name='compschedulequotation',
            name='quote2_path',
            field=models.CharField(default='#', max_length=500),
        ),
        migrations.AlterField(
            model_name='compschedulequotation',
            name='quote3_path',
            field=models.CharField(default='#', max_length=500),
        ),
        migrations.AlterField(
            model_name='paymentrequestpop',
            name='quote_path1',
            field=models.CharField(default='#', max_length=500),
        ),
        migrations.AlterField(
            model_name='paymentrequestquotation',
            name='quote_path1',
            field=models.CharField(default='#', max_length=500),
        ),
        migrations.AlterField(
            model_name='paymentrequestquotation1',
            name='quote_path1',
            field=models.CharField(default='#', max_length=500),
        ),
        migrations.AlterField(
            model_name='paymentrequestquotation1',
            name='quote_path2',
            field=models.CharField(default='#', max_length=500),
        ),
        migrations.AlterField(
            model_name='puchaserequestquotation',
            name='quote_path',
            field=models.CharField(default='#', max_length=500),
        ),
        migrations.AlterField(
            model_name='purchaseorderquotation',
            name='quote_path',
            field=models.CharField(default='#', max_length=500),
        ),
    ]
