# Generated by Django 4.2.8 on 2024-01-19 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='puchaserequest',
            old_name='rejector',
            new_name='rejector1',
        ),
        migrations.RenameField(
            model_name='puchaserequest',
            old_name='rejector_date',
            new_name='rejector1_date',
        ),
        migrations.RenameField(
            model_name='puchaserequest',
            old_name='rejector_message',
            new_name='rejector1_message',
        ),
    ]
