# Generated by Django 4.2.8 on 2023-12-16 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comparativeschedule',
            name='dpt_project_requesting',
        ),
        migrations.RemoveField(
            model_name='comparativeschedule',
            name='item_number_supplier1',
        ),
        migrations.RemoveField(
            model_name='comparativeschedule',
            name='item_number_supplier2',
        ),
        migrations.RemoveField(
            model_name='comparativeschedule',
            name='item_number_supplier3',
        ),
        migrations.RemoveField(
            model_name='comparativeschedule',
            name='payee',
        ),
        migrations.RemoveField(
            model_name='comparativeschedule',
            name='project_number',
        ),
        migrations.RemoveField(
            model_name='comparativeschedule',
            name='request_id',
        ),
        migrations.RemoveField(
            model_name='comparativeschedule',
            name='service_request',
        ),
        migrations.AddField(
            model_name='comparativeschedule',
            name='item_name_supplier1',
            field=models.CharField(default='None', max_length=450),
        ),
        migrations.AddField(
            model_name='comparativeschedule',
            name='item_name_supplier2',
            field=models.CharField(default='None', max_length=450),
        ),
        migrations.AddField(
            model_name='comparativeschedule',
            name='item_name_supplier3',
            field=models.CharField(default='None', max_length=450),
        ),
        migrations.AddField(
            model_name='comparativeschedule',
            name='purchase_request',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
