# Generated by Django 4.2.8 on 2024-01-24 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_budgetlines_department_project_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentticket',
            name='completed',
        ),
        migrations.AddField(
            model_name='supplier',
            name='rejector',
            field=models.CharField(default='None', max_length=150),
        ),
        migrations.AddField(
            model_name='supplier',
            name='rejector_date',
            field=models.CharField(default='None', max_length=500),
        ),
        migrations.AddField(
            model_name='supplier',
            name='rejector_message',
            field=models.CharField(default='None', max_length=500),
        ),
    ]
