# Generated by Django 4.1.7 on 2023-04-06 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_comparativeschedule_company_name_supplier1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrequest',
            name='qnty',
            field=models.CharField(default='None', max_length=150),
        ),
    ]
