# Generated by Django 4.2.8 on 2024-04-03 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='satisfied',
            field=models.CharField(default='0', max_length=255),
        ),
    ]
