# Generated by Django 3.2.6 on 2023-04-21 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_paymentrequestquotation'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='None', max_length=30)),
                ('contact_person', models.CharField(default='None', max_length=30)),
                ('contact_number', models.CharField(default='2023', max_length=25)),
                ('address', models.CharField(default='None', max_length=150)),
                ('project', models.CharField(default='None', max_length=450)),
                ('date', models.CharField(default='None', max_length=550)),
                ('budget_line_item', models.CharField(default='None', max_length=150)),
                ('item', models.CharField(default='None', max_length=150)),
                ('dept', models.FileField(default='None', upload_to='')),
                ('quantity', models.CharField(default='None', max_length=150)),
                ('description', models.CharField(default='None', max_length=150)),
                ('unit_cost', models.CharField(default='None', max_length=150)),
                ('total_cost', models.CharField(default='None', max_length=150)),
                ('ordered_by', models.CharField(default='None', max_length=150)),
                ('ordered_by_date', models.CharField(default='None', max_length=150)),
                ('required_by', models.CharField(default='None', max_length=150)),
                ('required_by_date', models.CharField(default='None', max_length=150)),
                ('approved_by', models.CharField(default='None', max_length=150)),
            ],
        ),
    ]
