# Generated by Django 4.2.8 on 2023-12-17 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_purchaseorder_comp_schedule_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentrequest',
            name='account_code',
        ),
        migrations.RemoveField(
            model_name='paymentrequest',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='paymentrequest',
            name='approved_by_date',
        ),
        migrations.RemoveField(
            model_name='paymentrequest',
            name='approved_by_project_man',
        ),
        migrations.RemoveField(
            model_name='paymentrequest',
            name='approved_by_project_man_date',
        ),
        migrations.RemoveField(
            model_name='paymentrequest',
            name='project_number',
        ),
    ]
