# Generated by Django 4.1.7 on 2023-04-09 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_paymentrequest_qnty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comparativeschedule',
            name='approved_by',
            field=models.CharField(default='None', max_length=30),
        ),
        migrations.AlterField(
            model_name='comparativeschedule',
            name='approved_by_sig',
            field=models.CharField(default='None', max_length=30),
        ),
        migrations.AlterField(
            model_name='comparativeschedule',
            name='approved_date',
            field=models.CharField(default='None', max_length=30),
        ),
        migrations.AlterField(
            model_name='comparativeschedule',
            name='dpt_head_by',
            field=models.CharField(default='None', max_length=30),
        ),
        migrations.AlterField(
            model_name='comparativeschedule',
            name='dpt_head_by_sig',
            field=models.CharField(default='None', max_length=30),
        ),
        migrations.AlterField(
            model_name='comparativeschedule',
            name='dpt_head_date',
            field=models.CharField(default='None', max_length=30),
        ),
        migrations.AlterField(
            model_name='comparativeschedule',
            name='request_id',
            field=models.CharField(default='None', max_length=30),
        ),
        migrations.AlterField(
            model_name='comparativeschedule',
            name='requested_by',
            field=models.CharField(default='None', max_length=30),
        ),
        migrations.AlterField(
            model_name='comparativeschedule',
            name='requested_by_date',
            field=models.CharField(default='None', max_length=30),
        ),
        migrations.AlterField(
            model_name='comparativeschedule',
            name='requested_by_sig',
            field=models.CharField(default='None', max_length=30),
        ),
        migrations.AlterField(
            model_name='comparativeschedule',
            name='team_lead_by',
            field=models.CharField(default='None', max_length=30),
        ),
        migrations.AlterField(
            model_name='comparativeschedule',
            name='team_lead_by_sig',
            field=models.CharField(default='None', max_length=30),
        ),
        migrations.AlterField(
            model_name='comparativeschedule',
            name='team_lead_date',
            field=models.CharField(default='None', max_length=30),
        ),
        migrations.AlterField(
            model_name='comparativeschedule',
            name='tech_person_by',
            field=models.CharField(default='None', max_length=30),
        ),
        migrations.AlterField(
            model_name='comparativeschedule',
            name='tech_person_by_sig',
            field=models.CharField(default='None', max_length=30),
        ),
        migrations.AlterField(
            model_name='comparativeschedule',
            name='tech_person_date',
            field=models.CharField(default='None', max_length=30),
        ),
        migrations.AlterField(
            model_name='paymentrequest',
            name='compiled_by',
            field=models.CharField(default='None', max_length=30),
        ),
        migrations.AlterField(
            model_name='paymentrequest',
            name='request_id',
            field=models.CharField(default='None', max_length=30),
        ),
        migrations.AlterField(
            model_name='puchaserequest',
            name='request_id',
            field=models.CharField(default='None', max_length=30),
        ),
        migrations.AlterField(
            model_name='puchaserequest',
            name='requester',
            field=models.CharField(default='None', max_length=30),
        ),
    ]
