# Generated by Django 4.2.8 on 2024-04-03 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_service_satisfied'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='created_by',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
