# Generated by Django 4.1.7 on 2023-04-24 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_purchaseorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='puchaserequest',
            name='request_id',
        ),
        migrations.AddField(
            model_name='puchaserequest',
            name='schedule_id',
            field=models.CharField(default='None', max_length=30),
        ),
    ]
