# Generated by Django 4.1.7 on 2023-04-12 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_comparativeschedule_approved_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger', models.CharField(max_length=220)),
                ('date_time', models.CharField(max_length=120)),
                ('message', models.CharField(max_length=420)),
                ('to', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=220)),
            ],
        ),
    ]
