# Generated by Django 4.1.7 on 2023-04-24 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_puchaserequest_request_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompScheduleQuotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(blank=True, max_length=255)),
                ('quote1_path', models.CharField(default='.', max_length=500)),
                ('quote2_path', models.CharField(default='.', max_length=500)),
                ('quote3_path', models.CharField(default='.', max_length=500)),
            ],
        ),
    ]
