# Generated by Django 4.2.8 on 2023-12-20 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_paymentrequest_account_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsReceivedNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_order', models.CharField(default='None', max_length=220)),
                ('payment_request', models.CharField(default='None', max_length=220)),
                ('status', models.CharField(default='None', max_length=220)),
                ('supplier', models.CharField(default='None', max_length=220)),
                ('dpt', models.CharField(default='None', max_length=220)),
                ('item_name', models.CharField(default='None', max_length=220)),
                ('desc', models.CharField(default='None', max_length=220)),
                ('qnty', models.CharField(default='None', max_length=220)),
                ('serial', models.CharField(default='None', max_length=220)),
                ('comments', models.CharField(default='None', max_length=220)),
                ('receiver', models.CharField(default='None', max_length=220)),
                ('approver', models.CharField(default='None', max_length=220)),
                ('receiver_date', models.CharField(default='None', max_length=220)),
                ('approver_date', models.CharField(default='None', max_length=220)),
            ],
        ),
        migrations.CreateModel(
            name='GoodsReceivedNoteDnote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(blank=True, max_length=255)),
                ('dnote_path', models.CharField(default='#', max_length=500)),
            ],
        ),
    ]
