# Generated by Django 4.2.8 on 2024-01-19 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_goodsreceivednote_goodsreceivednotednote'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='None', max_length=150)),
                ('address', models.CharField(default='None', max_length=150)),
                ('bank_name', models.CharField(default='None', max_length=150)),
                ('bank_branch', models.CharField(default='None', max_length=150)),
                ('bank_account', models.CharField(default='None', max_length=150)),
                ('contact_person', models.CharField(default='None', max_length=150)),
                ('contact_number', models.CharField(default='None', max_length=150)),
                ('contact_email', models.CharField(default='None', max_length=150)),
                ('vat_valid_expiry_date', models.CharField(default='.', max_length=150)),
                ('tax_clearance_expiry_date', models.CharField(default='.', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='SupplierDocs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_id', models.CharField(default='None', max_length=150)),
                ('vat_path', models.CharField(default='#', max_length=500)),
                ('tax_clearance_path', models.CharField(default='#', max_length=500)),
                ('profile_path', models.CharField(default='#', max_length=500)),
                ('certificate_path', models.CharField(default='#', max_length=500)),
            ],
        ),
    ]
