# Generated by Django 4.1.7 on 2023-04-25 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_compschedulequotation'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrequest',
            name='purchase_id',
            field=models.CharField(default='None', max_length=30),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='purchase_id',
            field=models.CharField(default='None', max_length=30),
        ),
        migrations.AlterField(
            model_name='paymentrequest',
            name='date_of_request',
            field=models.CharField(default='None', max_length=25),
        ),
    ]
