# Generated by Django 4.1.7 on 2023-04-15 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_notifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puchaserequest',
            name='date_of_request',
            field=models.CharField(default='2023', max_length=25),
        ),
    ]
