# Generated by Django 4.2.8 on 2024-01-19 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_supplier_supplierdocs'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProcurementRequests',
        ),
        migrations.DeleteModel(
            name='ProcurementRequests1',
        ),
        migrations.DeleteModel(
            name='ServiceRequest',
        ),
        migrations.AddField(
            model_name='comparativeschedule',
            name='rejector',
            field=models.CharField(default='None', max_length=150),
        ),
        migrations.AddField(
            model_name='comparativeschedule',
            name='rejector_date',
            field=models.CharField(default='None', max_length=1500),
        ),
        migrations.AddField(
            model_name='comparativeschedule',
            name='rejector_message',
            field=models.CharField(default='None', max_length=1500),
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='rejector',
            field=models.CharField(default='None', max_length=150),
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='rejector_date',
            field=models.CharField(default='None', max_length=1500),
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='rejector_message',
            field=models.CharField(default='None', max_length=1500),
        ),
        migrations.AddField(
            model_name='puchaserequest',
            name='rejector',
            field=models.CharField(default='None', max_length=150),
        ),
        migrations.AddField(
            model_name='puchaserequest',
            name='rejector_date',
            field=models.CharField(default='None', max_length=1500),
        ),
        migrations.AddField(
            model_name='puchaserequest',
            name='rejector_message',
            field=models.CharField(default='None', max_length=1500),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='rejector',
            field=models.CharField(default='None', max_length=150),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='rejector_date',
            field=models.CharField(default='None', max_length=1500),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='rejector_message',
            field=models.CharField(default='None', max_length=1500),
        ),
    ]
