# Generated by Django 4.1.7 on 2023-04-16 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_puchaserequest_date_of_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentrequest',
            name='approved_by_date',
            field=models.CharField(default='None', max_length=25),
        ),
        migrations.AlterField(
            model_name='paymentrequest',
            name='approved_by_project_man',
            field=models.CharField(default='None', max_length=250),
        ),
        migrations.AlterField(
            model_name='paymentrequest',
            name='approved_by_project_man_date',
            field=models.CharField(default='None', max_length=25),
        ),
        migrations.AlterField(
            model_name='paymentrequest',
            name='cleared_by_fin_man_date',
            field=models.CharField(default='None', max_length=25),
        ),
        migrations.AlterField(
            model_name='paymentrequest',
            name='date_of_request',
            field=models.CharField(default='2023', max_length=25),
        ),
    ]
