# Generated by Django 3.2.6 on 2023-04-25 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_paymentrequest_purchase_id_purchaseorder_purchase_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrderQuotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(blank=True, max_length=255)),
                ('quote_path', models.CharField(default='.', max_length=500)),
            ],
        ),
    ]
