# Generated by Django 3.2.6 on 2023-04-17 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_paymentrequest_approved_by_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comparativeschedule',
            name='upload',
            field=models.FileField(default='N/A', upload_to='documents/'),
        ),
    ]
