# Generated by Django 4.1.7 on 2023-04-17 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_paymentrequest_approved_by_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='puchaserequest',
            name='q1',
            field=models.FileField(default='None', upload_to=''),
        ),
    ]
