# Generated by Django 4.1.7 on 2023-07-05 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_purchaseorder_approved_by_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requester', models.CharField(default='None', max_length=30)),
                ('date_of_request', models.CharField(default='2023', max_length=25)),
                ('requesting_dpt', models.CharField(default='None', max_length=150)),
                ('request_justification', models.CharField(default='None', max_length=450)),
                ('qnty', models.CharField(default='None', max_length=150)),
                ('q1', models.FileField(default='None', upload_to='')),
                ('description', models.CharField(default='None', max_length=150)),
                ('supervisor_approved', models.CharField(default='None', max_length=150)),
                ('supervisor_approved_date', models.CharField(default='None', max_length=150)),
            ],
        ),
    ]
