# Generated by Django 4.1.6 on 2023-04-18 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0008_comparativeschedule_upload"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comparativeschedule",
            name="upload",
        ),
        migrations.AddField(
            model_name="comparativeschedule",
            name="upload_name",
            field=models.CharField(default="None", max_length=550),
        ),
    ]
