# Generated by Django 4.1.7 on 2023-07-05 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_servicerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='supervisor_disapproved_date',
            field=models.CharField(default='None', max_length=150),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='supervisor_disapproved_message',
            field=models.CharField(default='.', max_length=1500),
        ),
    ]
