# Generated by Django 3.2.6 on 2023-09-26 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_servicerequest_supervisor_disapproved_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentRequestQuotation1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(blank=True, max_length=255)),
                ('quote_path1', models.CharField(default='.', max_length=500)),
                ('quote_path2', models.CharField(default='.', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='ProcurementRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_request_id', models.CharField(default='None', max_length=300)),
                ('requester', models.CharField(default='None', max_length=300)),
                ('date_of_request', models.CharField(default='2023', max_length=250)),
                ('cost_category', models.CharField(default='None', max_length=150)),
                ('procurement_officer', models.CharField(default='None', max_length=150)),
                ('procurement_officer_accept', models.CharField(default='None', max_length=150)),
                ('procurement_officer_reject', models.CharField(default='None', max_length=150)),
                ('procurement_officer_reject_msg', models.CharField(default='None', max_length=350)),
            ],
        ),
        migrations.RenameField(
            model_name='paymentrequestquotation',
            old_name='quote_path',
            new_name='quote_path1',
        ),
        migrations.AddField(
            model_name='comparativeschedule',
            name='service_request',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='type_of_payment',
            field=models.CharField(default='None', max_length=550),
        ),
        migrations.AddField(
            model_name='paymentrequestquotation',
            name='quote_path2',
            field=models.CharField(default='#', max_length=500),
        ),
        migrations.AddField(
            model_name='puchaserequest',
            name='service_request',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='compiled_by',
            field=models.CharField(default='None', max_length=150),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='po',
            field=models.CharField(default='None', max_length=150),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='po_approved_date',
            field=models.CharField(default='None', max_length=150),
        ),
        migrations.AlterField(
            model_name='comparativeschedule',
            name='approved_by',
            field=models.CharField(default='None', max_length=300),
        ),
        migrations.AlterField(
            model_name='comparativeschedule',
            name='approved_by_sig',
            field=models.CharField(default='None', max_length=300),
        ),
        migrations.AlterField(
            model_name='comparativeschedule',
            name='approved_date',
            field=models.CharField(default='None', max_length=300),
        ),
        migrations.AlterField(
            model_name='comparativeschedule',
            name='dpt_head_by',
            field=models.CharField(default='None', max_length=300),
        ),
        migrations.AlterField(
            model_name='comparativeschedule',
            name='dpt_head_by_sig',
            field=models.CharField(default='None', max_length=300),
        ),
        migrations.AlterField(
            model_name='comparativeschedule',
            name='dpt_head_date',
            field=models.CharField(default='None', max_length=300),
        ),
        migrations.AlterField(
            model_name='comparativeschedule',
            name='dpt_project_requesting',
            field=models.CharField(default='2023', max_length=150),
        ),
        migrations.AlterField(
            model_name='comparativeschedule',
            name='recommended_supplier',
            field=models.CharField(default='2023', max_length=150),
        ),
        migrations.AlterField(
            model_name='comparativeschedule',
            name='request_id',
            field=models.CharField(default='None', max_length=300),
        ),
        migrations.AlterField(
            model_name='comparativeschedule',
            name='requested_by',
            field=models.CharField(default='None', max_length=300),
        ),
        migrations.AlterField(
            model_name='comparativeschedule',
            name='requested_by_date',
            field=models.CharField(default='None', max_length=300),
        ),
        migrations.AlterField(
            model_name='comparativeschedule',
            name='requested_by_sig',
            field=models.CharField(default='None', max_length=300),
        ),
        migrations.AlterField(
            model_name='comparativeschedule',
            name='team_lead_by',
            field=models.CharField(default='None', max_length=300),
        ),
        migrations.AlterField(
            model_name='comparativeschedule',
            name='team_lead_by_sig',
            field=models.CharField(default='None', max_length=300),
        ),
        migrations.AlterField(
            model_name='comparativeschedule',
            name='team_lead_date',
            field=models.CharField(default='None', max_length=300),
        ),
        migrations.AlterField(
            model_name='comparativeschedule',
            name='tech_person_by',
            field=models.CharField(default='None', max_length=300),
        ),
        migrations.AlterField(
            model_name='comparativeschedule',
            name='tech_person_by_sig',
            field=models.CharField(default='None', max_length=300),
        ),
        migrations.AlterField(
            model_name='comparativeschedule',
            name='tech_person_date',
            field=models.CharField(default='None', max_length=300),
        ),
        migrations.AlterField(
            model_name='paymentrequest',
            name='approved_by_date',
            field=models.CharField(default='None', max_length=250),
        ),
        migrations.AlterField(
            model_name='paymentrequest',
            name='approved_by_project_man_date',
            field=models.CharField(default='None', max_length=250),
        ),
        migrations.AlterField(
            model_name='paymentrequest',
            name='cleared_by_fin_man_date',
            field=models.CharField(default='None', max_length=250),
        ),
        migrations.AlterField(
            model_name='paymentrequest',
            name='compiled_by',
            field=models.CharField(default='None', max_length=300),
        ),
        migrations.AlterField(
            model_name='paymentrequest',
            name='date_of_request',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='paymentrequest',
            name='purchase_id',
            field=models.CharField(default='None', max_length=300),
        ),
        migrations.AlterField(
            model_name='paymentrequest',
            name='request_id',
            field=models.CharField(default='None', max_length=300),
        ),
        migrations.AlterField(
            model_name='puchaserequest',
            name='budget_line_item',
            field=models.CharField(default='None', max_length=200),
        ),
        migrations.AlterField(
            model_name='puchaserequest',
            name='date_of_request',
            field=models.CharField(default='2023', max_length=200),
        ),
        migrations.AlterField(
            model_name='puchaserequest',
            name='request_justification',
            field=models.CharField(default='None', max_length=2000),
        ),
        migrations.AlterField(
            model_name='puchaserequest',
            name='requester',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='puchaserequest',
            name='schedule_id',
            field=models.CharField(default='None', max_length=310),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='contact_number',
            field=models.CharField(default='2023', max_length=250),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='contact_person',
            field=models.CharField(default='None', max_length=300),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='name',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='purchase_id',
            field=models.CharField(default='None', max_length=300),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='date_of_request',
            field=models.CharField(default='2023', max_length=100),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='requester',
            field=models.CharField(default='None', max_length=300),
        ),
    ]
